### ISSUE TITLE
Add scrubbing option for escaping HTML (instead of stripping)

### ISSUE THREAD

**Issue by sn3p** [rrrene/html_sanitize_ex#37]
At the moment it seems there's only options for stripping HTML. I think it would make sense to also add an option to escape HTML, e.g. `HtmlSanitizeEx.escape_html(html)`.

```ex
iex> HtmlSanitizeEx.escape_html("<strong>bold?</strong>")
"&lt;strong&gt;bold?&lt;/strong&gt;"
```

**Comment by rrrene** [comment]
Hi, sorry for the late reply, but I do think this is out-of-scope for this library.

What would be the benefit of offering this function? 

I am asking because I am sensing that there would be follow-up feature requests once this function is added, like "Let me control that some tags are stripped in some circumstances and escaped in others".

**Comment by sn3p** [comment]
Thanks for answering.

> Hi, sorry for the late reply, but I do think this is out-of-scope for this library.

I think escaping html is a nice addition to the library, as this is a very common way to sanitize.

> What would be the benefit of offering this function?

Long time passed since I created this issue, but I think I the reason was that I need to sanitize user input, ie. code blocks.
